#Asp.net core example 
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

jobs:
- job: Work
  steps:
  - script: |
      echo Hello, wold!
    displayName: 'Run a one-line script'

-job: ErrorHandler
  dependsOn: Work
  condition: failed()
  steps:
  - bash: |
      az boards work-item create \
        --title "Build $(build.buildNumber) failed" \
        --type bud \
        --org $(System.TeamFoundationCollectionUri) \
        --project $(System.TeamProject)
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'


- job: InstallApp.Net
  steps:
  - script: |
      echo -e $APPINSTALL dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
